# Generated by Django 4.2.1 on 2023-07-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todolist',
            new_name='taskList',
        ),
    ]
